# Generated by Django 4.1.3 on 2022-12-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdetails',
            name='emno',
            field=models.IntegerField(),
        ),
    ]
